const API = "http://localhost:8080";
let handoffTimer = null;

function ownsRoute(){return location.pathname.endsWith("/handoff");}
export function unmountHandoffCenter(){if(handoffTimer)clearInterval(handoffTimer);handoffTimer=null;document.querySelector(".ho-drawer")?.remove();}
const esc=(v)=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");
const fmt=(v,s="")=>v==null||v===""?"Insufficient Data":`${esc(v)}${s}`;
const time=(v)=>v?new Date(v).toLocaleString():"Insufficient Data";
function cls(v){const t=String(v||"").toLowerCase();if(/ready|accepted|successful|passed|approved|healthy|available|true/.test(t))return"good";if(/pending|queued|progress|retried|warning|normal/.test(t))return"warn";if(/failed|blocked|rejected|cancelled|offline|unavailable|critical|archived/.test(t))return"bad";return"neutral";}
const pill=(v)=>`<b class="ho-pill ${cls(v)}">${esc(v||"Insufficient Data")}</b>`;
function table(headers,rows,empty){return `<div class="ho-table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join("")}</tr>`).join(""):`<tr><td class="ho-empty-cell" colspan="${headers.length}">${esc(empty)}</td></tr>`}</tbody></table></div>`;}
async function request(path,options){const r=await fetch(`${API}${path}`,{cache:"no-store",...options});if(!r.ok)throw new Error(`${path} returned HTTP ${r.status}`);return r.json();}
async function post(path,body={}){return request(path,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});}
function download(name,payload){const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
const latestId=(d)=>d.history?.[0]?.handoffId||d.detail?.metadata?.handoffId;

function header(d){const b=d.badges||{};const badges=[["Production Live",b.productionLive?"Enabled":"No"],["Mock Data Disabled",b.mockDataDisabled?"Yes":"No"],["Validated Packages Only",b.validatedPackagesOnly?"Yes":"No"],["Last Handoff",fmt(b.lastHandoff)],["Handoff Success Rate",fmt(b.handoffSuccessRate,"%")]];return `<header class="ho-header"><div><p>MARKET INTELLIGENCE / HANDOFF</p><h1>${esc(d.title)}</h1><span>${esc(d.subtitle)}</span><div class="ho-badges">${badges.map(([a,c])=>`<label><small>${a}</small><strong>${esc(c)}</strong></label>`).join("")}</div></div><div class="ho-actions"><button class="primary" data-action="refresh">Refresh Handoffs</button><button data-action="create">Create Handoff</button><button data-action="submit-latest">Submit Selected</button><button data-action="retry-failed">Retry Failed</button><button data-action="export-latest">Export Handoff Report</button></div></header>`;}
function summary(s){const cards=[["Ready for Handoff",s.readyForHandoff],["Submitted Today",s.submittedToday],["Successful Handoffs",s.successfulHandoffs],["Failed Handoffs",s.failedHandoffs],["Pending Approval",s.pendingApproval],["Blocked Handoffs",s.blockedHandoffs],["Queued Handoffs",s.queuedHandoffs],["Retry Required",s.retryRequired],["Average Processing Time",fmt(s.averageProcessingTime,"ms")],["Handoff Success Rate",fmt(s.handoffSuccessRate,"%")]];return `<section class="ho-summary">${cards.map(([a,b])=>`<article class="${cls(b)}"><small>${a}</small><strong>${fmt(b)}</strong></article>`).join("")}</section>`;}
function workflow(rows){return `<section class="ho-panel"><div class="ho-panel-head"><div><h2>Handoff Workflow</h2><p>Validated intelligence packages move through approval, payload review, submission, and result tracking.</p></div><b>${rows.length} STEPS</b></div><ol class="ho-steps">${rows.map((r,i)=>`<li><small>Step ${i+1}</small><strong>${esc(r)}</strong></li>`).join("")}</ol></section>`;}
function ready(rows,blocked){return `<section class="ho-panel"><div class="ho-panel-head"><div><h2>Validated Package Selection</h2><p>Only packages with status Validated, sufficient readiness, no critical failures, and no archive flag appear here.</p></div><b>${rows.length} READY</b></div>${rows.length?table(["Package ID","Package Type","Instruments","Readiness","Confidence","Validation","Built At","Built By","Status"],rows.map(r=>[esc(r.packageId),esc(r.packageType),esc((r.instruments||[]).join(", ")),fmt(r.readinessScore,"%"),fmt(r.confidenceScore,"%"),pill(r.validationStatus),time(r.builtAt),esc(r.builtBy),pill(r.status)]),"No validated packages ready."):empty(blocked)}</section>`;}
function empty(blocked){return `<div class="ho-empty"><h2>No validated intelligence packages are ready for handoff.</h2><p>Build and validate a package before submitting it to downstream engines.</p><div class="ho-actions"><button data-route="/workspace/market-intelligence/package-builder">Open Package Builder</button><button data-route="/workspace/market-intelligence/validated-package">Open Validated Packages</button><button data-route="/workspace/market-intelligence/source-health-review">Run Source Health Review</button><button data-route="/workspace/market-intelligence/scoring-engine">Open Scoring Engine</button></div>${blocked?.length?table(["Package ID","Type","Status","Readiness","Validation"],blocked.map(r=>[esc(r.packageId),esc(r.packageType),pill(r.status),fmt(r.readinessScore,"%"),pill(r.validationStatus)]),"No blocked packages."):""}</div>`;}
function destinations(rows){return `<section class="ho-panel"><div class="ho-panel-head"><div><h2>Destination Engine Selection</h2><p>Engine health, queue status, payload version, and permissions.</p></div><b>${rows.length} DESTINATIONS</b></div>${table(["Destination","Engine Status","API Health","Queue","Payload Version","Last Successful Handoff","Permission"],rows.map(r=>[esc(r.destinationLabel),pill(r.engineStatus),pill(r.apiHealth),pill(r.queueStatus),esc(r.acceptedPayloadVersion),time(r.lastSuccessfulHandoff),esc(r.handoffPermissionRequired)]),"No destinations configured.")}</section>`;}
function payload(p){return `<section class="ho-panel"><div class="ho-panel-head"><div><h2>Handoff Payload Preview</h2><p>Payload metadata, package content, risks, conflicts, AI summary, and checksum.</p></div></div>${p?`<div class="ho-preview-grid">${[["Payload ID",p.payloadId],["Package ID",p.packageId],["Destination",p.destinationEngine],["Payload Version",p.payloadVersion],["Included Instruments",(p.includedInstruments||[]).join(", ")],["Included Modules",(p.includedModules||[]).join(", ")],["Risk Warnings",(p.riskWarnings||[]).join(", ")||"None"],["Conflicts",(p.conflicts||[]).length],["Checksum",p.checksum]].map(([a,b])=>`<span><small>${a}</small><strong>${esc(b)}</strong></span>`).join("")}</div><div class="ho-actions"><button data-action="validate-latest">Validate Schema</button><button data-copy="${esc(p.payloadId)}">Copy Payload ID</button><button data-action="export-latest">Export JSON</button><button data-route="/workspace/market-intelligence/package-builder">View Package</button></div>`:`<p>No handoff payload has been created yet.</p>`}</section>`;}
function approvals(rows){return `<section class="ho-panel"><div class="ho-panel-head"><div><h2>Approval Workflow</h2><p>Auto, supervisor, risk, admin, and compliance approval trail.</p></div></div>${table(["Approver Role","Approver Name","Status","Decision Time","Comment"],rows.map(r=>[esc(r.approverRole),esc(r.approverName),pill(r.status),time(r.decisionTime),esc(r.comment)]),"No approval trail available.")}</section>`;}
function queue(rows){return `<section class="ho-panel"><div class="ho-panel-head"><div><h2>Handoff Queue Monitor</h2><p>Queue state, timing, retry count, and errors.</p></div><b>${rows.length} QUEUED</b></div>${table(["Handoff ID","Package ID","Destination","Priority","Status","Queued At","Started At","Completed At","Processing Time","Retry Count","Error"],rows.map(r=>[esc(r.handoffId),esc(r.packageId),esc(r.destination),pill(r.priority),pill(r.status),time(r.queuedAt),time(r.startedAt),time(r.completedAt),fmt(r.processingTime,"ms"),fmt(r.retryCount),esc(r.error)]),"No handoffs in queue.")}</section>`;}
function history(rows){return `<section class="ho-panel"><div class="ho-panel-head"><div><h2>Handoff History</h2><p>All production handoff records.</p></div><b>${rows.length} HANDOFFS</b></div>${table(["Handoff ID","Package ID","Package Type","Destination","Instruments","Status","Submitted By","Submitted At","Accepted At","Processing Time","Retry Count","Result","Actions"],rows.map(r=>[`<button class="ho-link" data-open-handoff="${esc(r.handoffId)}">${esc(r.handoffId)}</button>`,esc(r.packageId),esc(r.packageType),esc(r.destinationEngine),esc((r.instruments||[]).join(", ")),pill(r.status),esc(r.submittedBy),time(r.submittedAt),time(r.acceptedAt),fmt(r.processingTime,"ms"),fmt(r.retryCount),esc(r.result),`<span class="ho-row-actions"><button data-retry="${esc(r.handoffId)}">Retry</button><button data-cancel="${esc(r.handoffId)}">Cancel</button><button data-export="${esc(r.handoffId)}">Export</button><button data-archive="${esc(r.handoffId)}">Archive</button></span>`]),"No handoff history yet.")}</section>`;}
function failures(rows){return `<section class="ho-panel"><div class="ho-panel-head"><div><h2>Failure and Rejection Review</h2><p>Failed, rejected, blocked, and retryable handoffs.</p></div><b>${rows.length} FAILURES</b></div>${table(["Handoff ID","Package ID","Destination","Failure Type","Error Message","Severity","Retryable","Recommended Fix","Status"],rows.map(r=>[esc(r.handoffId),esc(r.packageId),esc(r.destination),esc(r.failureType),esc(r.errorMessage),pill(r.severity),r.retryable?"Yes":"No",esc(r.recommendedFix),pill(r.status)]),"No failed or rejected handoffs.")}</section>`;}
function ai(a){return `<section class="ho-panel ho-ai"><div class="ho-panel-head"><div><h2>AI Handoff Interpretation</h2><p>Ready packages, blocked packages, healthy destinations, retry safety, and risk review.</p></div><div class="ho-actions"><button data-action="refresh">Regenerate Summary</button><button data-action="export-latest">Export Brief</button></div></div><p>${esc(a.summary)}</p>${table(["Field","Value"],[["Ready Packages",esc((a.readyPackages||[]).join(", ")||"None")],["Blocked Packages",esc((a.blockedPackages||[]).join(", ")||"None")],["Healthy Destinations",esc((a.healthyDestinations||[]).join(", ")||"None")],["Retry Guidance",esc(a.retryGuidance)],["Risks Needing Review",esc((a.riskReview||[]).join(", ")||"None")]],"No AI interpretation available.")}</section>`;}
function drawer(d){return `<aside class="ho-drawer"><button data-action="close-drawer">x</button><p>HANDOFF DETAIL</p><h2>${esc(d.metadata.handoffId)}</h2><div class="ho-preview-grid">${[["Package",d.metadata.packageId],["Destination",d.destination.destinationLabel],["Status",d.metadata.status],["Priority",d.metadata.priority],["Retry Count",d.metadata.retryCount],["Result",d.metadata.result]].map(([a,b])=>`<span><small>${a}</small><strong>${esc(b)}</strong></span>`).join("")}</div>${payload(d.payloadPreview)}${table(["Validation","Status","Detail"],d.validationResults.map(r=>[esc(r.checkName),pill(r.status),esc(r.detail)]),"No validations.")}${approvals(d.approvalTrail)}${failures(d.errorLogs.map(r=>({handoffId:r.handoff_id,packageId:r.package_id,destination:r.destination_key,failureType:r.failure_type,errorMessage:r.error_message,severity:r.severity,retryable:r.retryable,recommendedFix:r.recommended_fix,status:r.status})))}<div class="ho-actions"><button data-retry="${esc(d.metadata.handoffId)}">Retry Handoff</button><button data-cancel="${esc(d.metadata.handoffId)}">Cancel Handoff</button><button data-export="${esc(d.metadata.handoffId)}">Export Payload</button><button data-route="/workspace/market-intelligence/package-builder">Open Package</button><button data-route="/workspace/market-intelligence/scoring-engine">Open Destination Engine</button><button data-archive="${esc(d.metadata.handoffId)}">Archive Handoff</button></div></aside>`;}

export function renderHandoffCenter(d){return `<section class="ho-dashboard">${header(d)}${summary(d.summary)}${workflow(d.workflow)}${ready(d.packagesReady,d.blockedPackages)}${destinations(d.destinations)}${payload(d.payloadPreview)}<div class="ho-grid">${approvals(d.approvalWorkflow)}${queue(d.queue)}</div>${history(d.history)}${failures(d.failures)}${ai(d.aiSummary)}</section>`;}
function bindCommon(root,refresh){root.querySelectorAll("[data-route]").forEach(b=>b.addEventListener("click",()=>window.dispatchEvent(new CustomEvent("mi:navigate",{detail:{route:b.dataset.route}}))));root.querySelectorAll("[data-retry]").forEach(b=>b.addEventListener("click",()=>post(`/api/market-intelligence/handoff/${b.dataset.retry}/retry`).then(refresh)));root.querySelectorAll("[data-cancel]").forEach(b=>b.addEventListener("click",()=>post(`/api/market-intelligence/handoff/${b.dataset.cancel}/cancel`).then(refresh)));root.querySelectorAll("[data-archive]").forEach(b=>b.addEventListener("click",()=>post(`/api/market-intelligence/handoff/${b.dataset.archive}/archive`).then(refresh)));root.querySelectorAll("[data-export]").forEach(b=>b.addEventListener("click",async()=>download(`${b.dataset.export}.json`,await request(`/api/market-intelligence/handoff/${b.dataset.export}/export`))));root.querySelectorAll("[data-copy]").forEach(b=>b.addEventListener("click",()=>navigator.clipboard?.writeText(b.dataset.copy)));}
export function bindHandoffCenter(d){const root=document.querySelector("#intelligence-content"),refresh=()=>mountHandoffCenter();root.querySelector('[data-action="refresh"]')?.addEventListener("click",refresh);root.querySelectorAll('[data-action="create"]').forEach(b=>b.addEventListener("click",()=>post("/api/market-intelligence/handoff/create",{}).then(refresh)));root.querySelectorAll('[data-action="submit-latest"]').forEach(b=>b.addEventListener("click",()=>latestId(d)&&post(`/api/market-intelligence/handoff/${latestId(d)}/submit`).then(refresh)));root.querySelectorAll('[data-action="validate-latest"]').forEach(b=>b.addEventListener("click",()=>latestId(d)&&post(`/api/market-intelligence/handoff/${latestId(d)}/validate`).then(refresh)));root.querySelectorAll('[data-action="retry-failed"]').forEach(b=>b.addEventListener("click",()=>d.failures?.[0]?.handoffId&&post(`/api/market-intelligence/handoff/${d.failures[0].handoffId}/retry`).then(refresh)));root.querySelectorAll('[data-action="export-latest"]').forEach(b=>b.addEventListener("click",async()=>latestId(d)&&download(`${latestId(d)}.json`,await request(`/api/market-intelligence/handoff/${latestId(d)}/export`))));root.querySelectorAll("[data-open-handoff]").forEach(b=>b.addEventListener("click",async()=>{const detail=await request(`/api/market-intelligence/handoff/${b.dataset.openHandoff}`);document.querySelector(".ho-drawer")?.remove();document.body.insertAdjacentHTML("beforeend",drawer(detail));bindDrawer(refresh);}));bindCommon(root,refresh);}
function bindDrawer(refresh){const el=document.querySelector(".ho-drawer");el?.querySelector('[data-action="close-drawer"]')?.addEventListener("click",()=>el.remove());bindCommon(el,refresh);}
export async function mountHandoffCenter(){const root=document.querySelector("#intelligence-content");try{root.innerHTML=`<section class="ho-dashboard"><section class="ho-panel"><h1>Market Intelligence Handoff Center</h1><p>Loading handoff control center...</p></section></section>`;const d=await request("/api/market-intelligence/handoff");if(!ownsRoute())return;root.innerHTML=renderHandoffCenter(d);bindHandoffCenter(d);if(handoffTimer)clearInterval(handoffTimer);handoffTimer=setInterval(()=>{if(!document.hidden&&ownsRoute())mountHandoffCenter()},30000);}catch(e){root.innerHTML=`<section class="ho-dashboard"><section class="ho-panel ho-error"><h1>Market Intelligence Handoff Center</h1><p>${esc(e.message)}</p><button class="primary" id="ho-retry">Retry</button></section></section>`;document.querySelector("#ho-retry")?.addEventListener("click",mountHandoffCenter);}}
