// <auto-generated />
using System;
using Cacsms.Engine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cacsms.Engine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CacsmsEngineDbContext))]
    [Migration("20260627042654_AddCotPositioningSchema")]
    partial class AddCotPositioningSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("engine")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cacsms.Engine.Infrastructure.Persistence.Entities.CotPositioningRowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Bias")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("bias");

                    b.Property<int>("ChangeLong")
                        .HasColumnType("int")
                        .HasColumnName("change_long");

                    b.Property<int>("ChangeShort")
                        .HasColumnType("int")
                        .HasColumnName("change_short");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("currency_name");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("DisplayCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("display_code");

                    b.Property<int>("Long")
                        .HasColumnType("int")
                        .HasColumnName("long");

                    b.Property<int>("NetPositions")
                        .HasColumnType("int")
                        .HasColumnName("net_positions");

                    b.Property<decimal>("PercentChange")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("percent_change");

                    b.Property<int>("Short")
                        .HasColumnType("int")
                        .HasColumnName("short");

                    b.Property<Guid>("SnapshotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("snapshot_id");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("symbol");

                    b.HasKey("Id");

                    b.HasIndex("SnapshotId", "Symbol")
                        .IsUnique()
                        .HasDatabaseName("ux_cot_positioning_rows_snapshot_symbol");

                    b.ToTable("cot_positioning_rows", "engine");
                });

            modelBuilder.Entity("Cacsms.Engine.Infrastructure.Persistence.Entities.CotPositioningSnapshotEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Bias")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("bias");

                    b.Property<int>("CommercialNet")
                        .HasColumnType("int")
                        .HasColumnName("commercial_net");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("data_source");

                    b.Property<string>("InstitutionalSentiment")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)")
                        .HasColumnName("institutional_sentiment");

                    b.Property<decimal>("LongShortRatio")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnName("long_short_ratio");

                    b.Property<int>("NetPositionAll")
                        .HasColumnType("int")
                        .HasColumnName("net_position_all");

                    b.Property<int>("NonCommercialNet")
                        .HasColumnType("int")
                        .HasColumnName("non_commercial_net");

                    b.Property<int>("NonReportableNet")
                        .HasColumnType("int")
                        .HasColumnName("non_reportable_net");

                    b.Property<int>("OpenInterest")
                        .HasColumnType("int")
                        .HasColumnName("open_interest");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date")
                        .HasColumnName("release_date");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<string>("ReportingPeriod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("reporting_period");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("server");

                    b.Property<string>("ServerStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("server_status");

                    b.Property<int>("TotalContracts")
                        .HasColumnType("int")
                        .HasColumnName("total_contracts");

                    b.Property<int>("TotalLong")
                        .HasColumnType("int")
                        .HasColumnName("total_long");

                    b.Property<int>("TotalShort")
                        .HasColumnType("int")
                        .HasColumnName("total_short");

                    b.Property<int>("TotalTraders")
                        .HasColumnType("int")
                        .HasColumnName("total_traders");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate")
                        .IsDescending()
                        .HasDatabaseName("ix_cot_positioning_snapshots_report_date");

                    b.HasIndex("ReportDate", "DataSource")
                        .IsUnique()
                        .HasDatabaseName("ux_cot_positioning_snapshots_report_source");

                    b.ToTable("cot_positioning_snapshots", "engine");
                });

            modelBuilder.Entity("Cacsms.Engine.Infrastructure.Persistence.Entities.DecisionRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("ConfidenceScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("confidence_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("direction");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("recommendation");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_json");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("response_json");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("symbol");

                    b.Property<string>("TradingMode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("trading_mode");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending()
                        .HasDatabaseName("ix_decision_records_created_at");

                    b.ToTable("decision_records", "engine");
                });

            modelBuilder.Entity("Cacsms.Engine.Infrastructure.Persistence.Entities.CotPositioningRowEntity", b =>
                {
                    b.HasOne("Cacsms.Engine.Infrastructure.Persistence.Entities.CotPositioningSnapshotEntity", "Snapshot")
                        .WithMany("Rows")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Cacsms.Engine.Infrastructure.Persistence.Entities.CotPositioningSnapshotEntity", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
