namespace Cacsms.Engine.Application.Decisioning;

public sealed record HybridDecisionRequest(
    string Symbol,
    string TradingMode = "Hybrid",
    string Timeframe = "M15",
    string Session = "London",
    string MarketRegime = "Trending",
    string HigherTimeframeBias = "Neutral",
    string EntryTimeframeBias = "Neutral",
    decimal MultiTimeframeAlignmentScore = 50,
    decimal HigherTimeframeConflictScore = 100,
    decimal ExecutionTimeframeConfirmationScore = 50,
    decimal SpreadPoints = 0,
    decimal SlippagePoints = 0,
    decimal RiskReward = 0,
    bool NewsRisk = false,
    bool LiquiditySweep = false,
    bool Displacement = false,
    bool FairValueGap = false,
    bool OrderBlockRetest = false,
    bool BreakOfStructure = false,
    bool RetailTrendAligned = false,
    bool SupportResistanceConfirmation = false,
    bool PullbackConfirmation = false,
    decimal MacroBiasScore = 50,
    decimal InterestRateDifferentialScore = 50,
    decimal CotPositioningScore = 50,
    decimal CurrencyStrengthScore = 50,
    decimal MacroRiskScore = 50,
    decimal RegimeModelScore = 50,
    decimal HistoricalSimilarityScore = 50,
    decimal CandleIntelligenceScore = 50,
    decimal H8D1ProjectionScore = 50,
    decimal EnsemblePredictionScore = 50,
    decimal BayesianConfidenceScore = 50,
    decimal ProbabilityCalibrationScore = 50,
    decimal AnomalyScore = 100,
    decimal ExecutionQualityScore = 50,
    decimal VolatilityScore = 50,
    decimal StrategyHealthScore = 50,
    decimal AccountDrawdownPercent = 0,
    decimal DailyLossPercent = 0,
    int ConsecutiveLosses = 0,
    decimal RequestedRiskPercent = 0.25m);

public sealed record HybridDecisionResponse(
    string Symbol,
    string TradingMode,
    string Recommendation,
    string Direction,
    decimal ConfidenceScore,
    decimal TopDownBiasScore,
    decimal MacroScore,
    decimal AdvancedAlgorithmScore,
    decimal MarketMemoryScore,
    decimal InstitutionalScore,
    decimal RetailScore,
    decimal HybridScore,
    decimal ApprovedRiskPercent,
    string ApprovedStrategy,
    string LiquidityTarget,
    string InvalidationLevel,
    int ExpiresInMinutes,
    IReadOnlyCollection<string> NoTradeReasons,
    IReadOnlyCollection<string> Evidence);
