export const HISTORICAL_DATA_PERMISSIONS=Object.freeze(["market_intelligence.historical_data.view","market_intelligence.historical_data.export","market_intelligence.historical_data.sync","market_intelligence.historical_data.upload","market_intelligence.historical_data.configure_source","market_intelligence.historical_data.delete"]);
export const HISTORICAL_INSTRUMENTS=Object.freeze([["EURUSD","EUR/USD","forex",1.0842],["GBPUSD","GBP/USD","forex",1.2714],["USDJPY","USD/JPY","forex",156.42],["AUDUSD","AUD/USD","forex",0.6538],["USDCAD","USD/CAD","forex",1.3642],["USDCHF","USD/CHF","forex",0.9026],["NZDUSD","NZD/USD","forex",0.6128],["XAUUSD","XAU/USD","metals",2342.6],["XAGUSD","XAG/USD","metals",31.24],["US30","US30","indices",42180],["NAS100","NAS100","indices",18842],["SPX500","SPX500","indices",5288],["BTCUSD","BTC/USD","crypto",68240],["ETHUSD","ETH/USD","crypto",3820],["USOIL","USOIL","energy",78.42]].map(([id,label,assetClass,base])=>({id,label,assetClass,base})));
const dates=["2026-05-31","2026-05-30","2026-05-29","2026-05-28","2026-05-27","2026-05-26","2026-05-23","2026-05-22","2026-05-21","2026-05-20","2026-05-19","2026-05-16","2026-05-15","2026-05-14","2026-05-13","2026-05-12","2026-05-09","2026-05-08","2026-05-07","2026-05-06"];
const precision=id=>id.includes("JPY")?3:["US30","NAS100","SPX500","BTCUSD","ETHUSD","USOIL","XAUUSD","XAGUSD"].includes(id)?2:5;
function recordsFor(instrument){const meta=HISTORICAL_INSTRUMENTS.find(x=>x.id===instrument)||HISTORICAL_INSTRUMENTS[0],digits=precision(meta.id);return dates.map((date,index)=>{const wave=Math.sin(index*.82+(meta.id.charCodeAt(0)%5))*meta.base*.004,open=meta.base-wave-index*meta.base*.00035,close=open+Math.cos(index*.68)*meta.base*.0032,high=Math.max(open,close)+meta.base*.0024,low=Math.min(open,close)-meta.base*.0019,change=close-open,range=high-low,changePercent=change/open*100,trendBias=changePercent>.22?"Strong Bullish":changePercent>.03?"Bullish":changePercent<-.22?"Strong Bearish":changePercent<-.03?"Bearish":"Neutral";return{id:`${meta.id}-${date}`,instrument:meta.id,instrumentLabel:meta.label,assetClass:meta.assetClass,timeframe:"1D",date,time:"00:00",open:Number(open.toFixed(digits)),high:Number(high.toFixed(digits)),low:Number(low.toFixed(digits)),close:Number(close.toFixed(digits)),volume:Math.round(118000+index*1830+Math.abs(wave/meta.base)*980000),change:Number(change.toFixed(digits)),changePercent:Number(changePercent.toFixed(2)),range:Number(range.toFixed(digits)),volatility:Number((Math.abs(range/open)*100).toFixed(2)),trendBias,source:"Internal Database",createdAt:`${date}T00:05:00.000Z`,updatedAt:`${date}T08:30:00.000Z`}})}
export const HISTORICAL_DATA=Object.freeze(Object.fromEntries(HISTORICAL_INSTRUMENTS.map(x=>[x.id,Object.freeze(recordsFor(x.id))])));
export const HISTORICAL_SOURCES=Object.freeze([["FX Daily Feed","Twelve Data","ACTIVE","Today 08:30","120,540","0","12:00"],["Metals Feed","Yahoo Finance","ACTIVE","Today 08:20","48,320","0","12:00"],["Broker Feed","MetaTrader API","PENDING","-","0","0","Manual"],["Internal Warehouse","CACSMS Store","ACTIVE","Today 08:30","428,600,000","3","Continuous"]].map(([sourceName,provider,status,lastSync,recordsImported,failedRecords,nextSync])=>({sourceName,provider,status,lastSync,recordsImported,failedRecords,nextSync})));
export function getHistoricalSummary(instrument="EURUSD"){const records=HISTORICAL_DATA[instrument]||[];if(!records.length)return null;const latest=records[0],oldest=records.at(-1),highest=Math.max(...records.map(x=>x.high)),lowest=Math.min(...records.map(x=>x.low)),netChange=latest.close-oldest.open,percentChange=netChange/oldest.open*100,averageRange=records.reduce((sum,x)=>sum+x.range,0)/records.length,volatility=records.reduce((sum,x)=>sum+x.volatility,0)/records.length,totalVolume=records.reduce((sum,x)=>sum+x.volume,0);return{instrument,openingPrice:oldest.open,closingPrice:latest.close,highestPrice:highest,lowestPrice:lowest,netChange,percentChange,averageRange,volatility,totalVolume,trendBias:percentChange>.2?"Bullish":percentChange<-.2?"Bearish":"Neutral",lastUpdated:"Today, 08:30 AM"}}
export function getHistoricalComparison(instruments=["EURUSD","GBPUSD","XAUUSD"]){return instruments.map(instrument=>{const summary=getHistoricalSummary(instrument);return{instrument,return:Number(summary.percentChange.toFixed(2)),volatility:Number(summary.volatility.toFixed(2)),maxDrawdown:Number((-summary.volatility*.41).toFixed(2)),averageRange:Number(summary.averageRange.toFixed(5)),correlation:instrument==="EURUSD"?1:Number((.35+(instrument.charCodeAt(0)%6)/10).toFixed(2)),relativeStrength:summary.percentChange>.5?"Strong":"Moderate",bias:summary.trendBias}})}
export function getHistoricalDashboard({instrument="EURUSD"}={}){return{status:"SYNCED",lastUpdated:"Today, 08:30 AM",instrument,summary:getHistoricalSummary(instrument),records:HISTORICAL_DATA[instrument]||[],comparison:getHistoricalComparison(),sources:HISTORICAL_SOURCES,permissions:HISTORICAL_DATA_PERMISSIONS}}
