"use client";
import{useMemo,useState}from"react";import{historicalSample,historicalSources}from"../../../lib/market-intelligence/historical-data/mock-data";
export function HistoricalDataPage(){const[instrument,setInstrument]=useState("EURUSD"),[timeframe,setTimeframe]=useState("1D"),[chart,setChart]=useState("Candlestick");const summary=useMemo(()=>{const latest=historicalSample[0],oldest=historicalSample.at(-1)!;return{open:oldest.open,close:latest.close,high:Math.max(...historicalSample.map(x=>x.high)),low:Math.min(...historicalSample.map(x=>x.low)),net:latest.close-oldest.open,volume:historicalSample.reduce((s,x)=>s+(x.volume||0),0)}},[]);return <main className="icot-dashboard hdata-dashboard">
 <header className="icot-header"><div><span className="icot-eyebrow">MARKET INTELLIGENCE / HISTORICAL DATA</span><h1>Historical Data</h1><p>Analyze historical price movements, market structure, volatility, and trend behaviour across major trading instruments.</p></div><div className="icot-header-actions"><div><small>DATA STATUS</small><strong>SYNCED / TODAY 08:30 AM</strong></div><button className="icot-button secondary">Export CSV</button><button className="icot-button primary">Refresh Data</button></div></header>
 <section className="icot-panel"><h2>Historical Market Data Filters</h2><div className="hd-filter-grid"><label>Instrument<select value={instrument} onChange={e=>setInstrument(e.target.value)}><option>EURUSD</option><option>XAUUSD</option><option>NAS100</option></select></label><label>Timeframe<select value={timeframe} onChange={e=>setTimeframe(e.target.value)}><option>1D</option><option>4H</option><option>1H</option></select></label><label>Chart Type<select value={chart} onChange={e=>setChart(e.target.value)}><option>Candlestick</option><option>Line</option><option>Area</option></select></label></div></section>
 <section className="icot-kpis">{[["Opening Price",summary.open],["Closing Price",summary.close],["Highest Price",summary.high],["Lowest Price",summary.low],["Net Change",summary.net],["Total Volume",summary.volume]].map(([a,b])=><article className="icot-kpi" key={a}><small>{a}</small><strong>{Number(b).toLocaleString()}</strong><span>{instrument} / {timeframe}</span></article>)}</section>
 <section className="icot-panel"><h2>{instrument} Historical Price Movement</h2><p className="subtitle">{chart} chart with volume and moving-average overlay controls.</p></section>
 <section className="icot-panel"><h2>Historical OHLCV Data Table</h2><div className="icot-table-wrap"><table><thead><tr><th>Date</th><th>Instrument</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th><th>Trend Bias</th></tr></thead><tbody>{historicalSample.map(x=><tr key={x.id}><td>{x.date}</td><td>{x.instrument}</td><td>{x.open}</td><td>{x.high}</td><td>{x.low}</td><td>{x.close}</td><td>{x.volume}</td><td>{x.trendBias}</td></tr>)}</tbody></table></div></section>
 <section className="icot-panel"><h2>Data Source Integration</h2><div className="icot-table-wrap"><table><tbody>{historicalSources.map(x=><tr key={x.sourceName}><td>{x.sourceName}</td><td>{x.provider}</td><td>{x.status}</td><td>{x.lastSync}</td></tr>)}</tbody></table></div></section>
</main>}
