FROM node:20-alpine
WORKDIR /app

COPY package.json package-lock.json ./
COPY packages ./packages
COPY apps ./apps
COPY services ./services
RUN npm ci

COPY database ./database
COPY scripts ./scripts

CMD ["node", "scripts/run-migrations.mjs"]
