"use client";
const feeds=[["IC Markets","MT5","Raw Spread","Connected","0.7","18ms","99%"],["Pepperstone","cTrader","ECN","Connected","0.8","24ms","97%"],["Exness","REST API","Standard","Connected","1.1","31ms","94%"],["FTMO","MT5","Prop Firm","Pending","1.3","38ms","91%"]];
const validation=[["Missing candles","Warning","FTMO","EURUSD","Backfill from MT5 bridge"],["Duplicate candles","Info","Pepperstone","GBPUSD","Keep normalized record"],["Bid/ask inversion","Error","Exness","USOIL","Reject tick and inspect quote"],["Excessive spread","Warning","Exness","XAUUSD","Review liquidity threshold"]];
const sourceTypes=["MetaTrader Bridge","cTrader API","FIX API","REST API","CSV Upload","Manual Import"];
const table=(heads:string[],rows:string[][])=><div className="icot-table-wrap"><table><thead><tr>{heads.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.join("-")}>{row.map((x,i)=><td key={`${x}-${i}`}>{x}</td>)}</tr>)}</tbody></table></div>;
export function BrokerDataPage(){return <main className="icot-dashboard broker-dashboard"><header className="icot-header"><div><span className="icot-eyebrow">MARKET INTELLIGENCE / BROKER DATA</span><h1>Broker Data</h1><p>Monitor broker feeds, pricing quality, spreads, execution data, and historical broker market conditions.</p></div><div className="icot-header-actions"><button className="icot-button secondary">Upload Broker Export</button><button className="icot-button secondary">Export Report</button><button className="icot-button primary">Connect Broker</button></div></header>
<section className="icot-status-strip">{[["Connected Brokers","3"],["Active Feeds","3"],["Last Sync","10:58 UTC"],["Data Quality","95%"],["Avg Spread","0.98"],["Latency","28ms"],["Missing Candles","33"],["Rejected Records","1"]].map(([a,b])=><article key={a}><small>{a}</small><strong>{b}</strong></article>)}</section>
<section className="icot-panel"><h2>Broker Filter Panel</h2><p>Broker / account type / platform / instrument / timeframe / date range / data type</p></section>
<section className="icot-panel"><h2>Broker Feed Overview Table</h2>{table(["Broker","Platform","Account Type","Status","Spread","Latency","Quality"],feeds)}</section>
<section className="icot-panel"><h2>Main Broker Data Chart</h2><p>Candlestick / Line / Bid-Ask / Spread Area / Tick Density / Execution Slippage</p></section>
<section className="icot-panel"><h2>Broker Comparison Section</h2>{table(["Broker","EUR/USD Spread","Latency","Completeness","Quality"],feeds.map(x=>[x[0],x[4],x[5],"99%+",x[6]]))}</section>
<section className="icot-panel"><h2>Data Quality Validation Panel</h2>{table(["Rule","Severity","Broker","Instrument","Recommended Fix"],validation)}</section>
<section className="icot-panel"><h2>Broker Data Table</h2><p>Normalized bid, ask, OHLCV, tick count, latency and quality records with detail drawer support.</p></section>
<section className="icot-panel"><h2>Broker Source Configuration</h2><div className="portfolio-gates">{sourceTypes.map(x=><article key={x}><small>Source Type</small><strong>{x}</strong></article>)}</div></section>
<section className="icot-panel icot-actions"><h2>Broker Data Action Center</h2><div>{["Connect Broker","Sync Broker Data","Upload Broker Export","Validate All Feeds","Compare Brokers","Export Broker Report","Configure Sources","Disconnect Broker"].map((x,i)=><button className={`icot-button ${i<3?"primary":"secondary"}`} key={x}>{x}</button>)}</div></section></main>}
